services:
  postgres:
    image: postgres:latest
    container_name: trello-postgres
    environment:
      POSTGRES_USER: trello_user
      POSTGRES_PASSWORD: trello_pass
      POSTGRES_DB: trello_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
